# Generated by Django 5.0.2 on 2024-02-16 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_delete_react'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='id_pasta',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False),
        ),
    ]
