# Generated by Django 5.0.2 on 2024-02-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_app_id_pasta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='Pasta',
        ),
    ]
