# Generated by Django 5.0.2 on 2024-02-21 16:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_app_pasta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubPasta',
            fields=[
                ('id_subpasta', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('pasta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='app.pasta')),
            ],
        ),
    ]
