# Generated by Django 5.0.2 on 2024-02-21 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_subpasta_pasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasta',
            name='nome',
            field=models.CharField(default='New Folder', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='descricao',
            field=models.TextField(default='Description'),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='nome',
            field=models.CharField(default='NEW ARQUIVOS', max_length=20),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='app.pasta'),
        ),
    ]
