# Generated by Django 5.0.2 on 2024-02-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_pasta_nome_alter_subpasta_descricao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subpasta',
            old_name='pasta',
            new_name='id_pasta_pai',
        ),
    ]
