# Generated by Django 5.0.2 on 2024-02-26 18:37

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_pasta_subpasta_id_pasta_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpasta',
            name='id_subpasta',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
