# Generated by Django 5.0.2 on 2024-02-27 14:54

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_subpasta_id_subpasta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subpasta',
            name='id_subpasta',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='BoardApp',
            fields=[
                ('id_board_app', models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False)),
                ('url_youtube', models.CharField(max_length=100)),
                ('anotacoes', models.TextField(default='anoracoes')),
                ('transcricao', models.TextField(default='transcricao')),
                ('resumo', models.TextField(default='resumo')),
                ('ai', models.TextField(default='ai')),
                ('min_importante', models.TextField(default='min_importante do video')),
                ('id_subpasta_pai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boardapp', to='app.subpasta')),
            ],
        ),
    ]
