# Generated by Django 5.0.2 on 2024-02-27 15:06

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_boardapp_id_board_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardapp',
            name='ai',
            field=models.TextField(blank=True, default='ai', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='anotacoes',
            field=models.TextField(blank=True, default='anotacoes', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='id_board_app',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='id_subpasta_pai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boardapp', to='app.subpasta'),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='min_importante',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='resumo',
            field=models.TextField(blank=True, default='resumo', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='transcricao',
            field=models.TextField(blank=True, default='transcricao', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='url_youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='id_subpasta',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
