# Generated by Django 5.0.2 on 2024-02-27 15:08

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_boardapp_ai_alter_boardapp_anotacoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardapp',
            name='id_board_app',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='id_subpasta',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
