# Generated by Django 5.0.2 on 2024-02-28 13:00

import django.db.models.deletion
import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_boardapp_id_board_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardapp',
            name='ai',
            field=models.TextField(blank=True, default='AI', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='anotacoes',
            field=models.TextField(blank=True, default='Anotações', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='id_board_app',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='id_subpasta_pai',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subpastas', to='app.subpasta'),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='resumo',
            field=models.TextField(blank=True, default='Resumo', null=True),
        ),
        migrations.AlterField(
            model_name='boardapp',
            name='transcricao',
            field=models.TextField(blank=True, default='Transcrição', null=True),
        ),
        migrations.AlterField(
            model_name='subpasta',
            name='id_subpasta',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, editable=False, max_length=22, primary_key=True, serialize=False),
        ),
    ]
